// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SilentID.Api.Data;

#nullable disable

namespace SilentID.Api.Migrations
{
    [DbContext(typeof(SilentIdDbContext))]
    partial class SilentIdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SilentID.Api.Models.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AdminUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminUser");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetUserId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("SilentID.Api.Models.AuthDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OS")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("AuthDevices");
                });

            modelBuilder.Entity("SilentID.Api.Models.ExternalRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountAge")
                        .HasColumnType("integer");

                    b.Property<decimal>("AccountAgeWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CombinedWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NormalizedRating")
                        .HasColumnType("numeric");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PlatformRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProfileLinkId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ReviewCountWeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightedScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProfileLinkId");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalRatings");
                });

            modelBuilder.Entity("SilentID.Api.Models.IdentityVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeVerificationId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StripeVerificationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("IdentityVerifications");
                });

            modelBuilder.Entity("SilentID.Api.Models.MutualVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FraudFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RoleA")
                        .HasColumnType("integer");

                    b.Property<int>("RoleB")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("MutualVerifications");
                });

            modelBuilder.Entity("SilentID.Api.Models.PasskeyCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AaGuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("AttestationFormat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("public-key");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UserVerified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasskeyCredentials");
                });

            modelBuilder.Entity("SilentID.Api.Models.PlatformConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiConfigJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("AvgConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<int>("BackoffStrategy")
                        .HasColumnType("integer");

                    b.Property<string>("BioFieldSelector")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BioFieldXPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BrandColor")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("JoinDateSelectorsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastExtractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("integer");

                    b.Property<int>("RatingFormat")
                        .HasColumnType("integer");

                    b.Property<decimal>("RatingMax")
                        .HasColumnType("numeric");

                    b.Property<string>("RatingSelectorsJson")
                        .HasColumnType("text");

                    b.Property<int>("RatingSourceMode")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewCountSelectorsJson")
                        .HasColumnType("text");

                    b.Property<int>("SelectorVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ShareIntentPatternsJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlPatternsJson")
                        .HasColumnType("text");

                    b.Property<string>("UsernameSelectorsJson")
                        .HasColumnType("text");

                    b.Property<string>("VerificationMethodsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("PlatformId")
                        .IsUnique();

                    b.ToTable("PlatformConfigurations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BackoffStrategy = 0,
                            BioFieldSelector = "div[data-testid='user-about'] p",
                            BrandColor = "#09B1BA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Vinted UK",
                            Domain = "vinted.co.uk",
                            LogoUrl = "https://assets.vinted.com/logo.png",
                            PlatformId = "vinted-uk",
                            RateLimitPerMinute = 10,
                            RatingFormat = 0,
                            RatingMax = 5.0m,
                            RatingSelectorsJson = "[{\"priority\":1,\"selector\":\"div[data-testid='user-rating'] span\",\"type\":\"css\"}]",
                            RatingSourceMode = 1,
                            ReviewCountSelectorsJson = "[{\"priority\":1,\"selector\":\"span[data-testid='review-count']\",\"type\":\"css\"}]",
                            SelectorVersion = 1,
                            ShareIntentPatternsJson = "[\"vinted://member/([^/]+)\"]",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UrlPatternsJson = "[\"https?://(?:www\\\\.)?vinted\\\\.co\\\\.uk/member/([^/]+)\"]",
                            UsernameSelectorsJson = "[{\"priority\":1,\"selector\":\"h1[data-testid='username']\",\"type\":\"css\"}]",
                            VerificationMethodsJson = "[\"ShareIntent\",\"TokenInBio\"]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BackoffStrategy = 0,
                            BioFieldSelector = "div.bio span.desc",
                            BrandColor = "#E53238",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "eBay UK",
                            Domain = "ebay.co.uk",
                            LogoUrl = "https://ir.ebaystatic.com/logo.png",
                            PlatformId = "ebay-uk",
                            RateLimitPerMinute = 10,
                            RatingFormat = 1,
                            RatingMax = 100.0m,
                            RatingSelectorsJson = "[{\"priority\":1,\"selector\":\"span.star-rating span.num\",\"type\":\"css\"}]",
                            RatingSourceMode = 1,
                            ReviewCountSelectorsJson = "[{\"priority\":1,\"selector\":\"span.reviews a\",\"type\":\"css\"}]",
                            SelectorVersion = 1,
                            ShareIntentPatternsJson = "[\"ebay://user/([^/]+)\"]",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UrlPatternsJson = "[\"https?://(?:www\\\\.)?ebay\\\\.co\\\\.uk/usr/([^/?]+)\"]",
                            UsernameSelectorsJson = "[{\"priority\":1,\"selector\":\"h1.usr-id\",\"type\":\"css\"}]",
                            VerificationMethodsJson = "[\"ShareIntent\",\"TokenInBio\"]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BackoffStrategy = 0,
                            BioFieldSelector = "p[data-testid='sellerBio']",
                            BrandColor = "#FF2300",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Depop",
                            Domain = "depop.com",
                            LogoUrl = "https://assets.depop.com/logo.png",
                            PlatformId = "depop",
                            RateLimitPerMinute = 10,
                            RatingFormat = 0,
                            RatingMax = 5.0m,
                            RatingSelectorsJson = "[{\"priority\":1,\"selector\":\"div[data-testid='seller-reviews'] span\",\"type\":\"css\"}]",
                            RatingSourceMode = 1,
                            ReviewCountSelectorsJson = "[{\"priority\":1,\"selector\":\"span[data-testid='reviews-count']\",\"type\":\"css\"}]",
                            SelectorVersion = 1,
                            ShareIntentPatternsJson = "[\"depop://user/([^/]+)\"]",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UrlPatternsJson = "[\"https?://(?:www\\\\.)?depop\\\\.com/([^/?]+)\"]",
                            UsernameSelectorsJson = "[{\"priority\":1,\"selector\":\"h1[data-testid='username']\",\"type\":\"css\"}]",
                            VerificationMethodsJson = "[\"ShareIntent\",\"TokenInBio\"]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BackoffStrategy = 0,
                            BrandColor = "#1877F2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Facebook Marketplace",
                            Domain = "facebook.com",
                            LogoUrl = "https://static.xx.fbcdn.net/logo.png",
                            PlatformId = "facebook-marketplace",
                            RateLimitPerMinute = 5,
                            RatingFormat = 0,
                            RatingMax = 5.0m,
                            RatingSelectorsJson = "[{\"priority\":1,\"selector\":\"span[data-testid='rating-value']\",\"type\":\"css\"}]",
                            RatingSourceMode = 1,
                            ReviewCountSelectorsJson = "[{\"priority\":1,\"selector\":\"span[data-testid='rating-count']\",\"type\":\"css\"}]",
                            SelectorVersion = 1,
                            ShareIntentPatternsJson = "[\"fb://marketplace/profile/([0-9]+)\"]",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UrlPatternsJson = "[\"https?://(?:www\\\\.)?facebook\\\\.com/marketplace/profile/([0-9]+)\"]",
                            VerificationMethodsJson = "[\"ShareIntent\"]"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BackoffStrategy = 0,
                            BioFieldSelector = "div.about-section p",
                            BrandColor = "#7F0353",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Poshmark",
                            Domain = "poshmark.com",
                            LogoUrl = "https://assets.poshmark.com/logo.png",
                            PlatformId = "poshmark",
                            RateLimitPerMinute = 10,
                            RatingFormat = 0,
                            RatingMax = 5.0m,
                            RatingSelectorsJson = "[{\"priority\":1,\"selector\":\"span.love-count\",\"type\":\"css\"}]",
                            RatingSourceMode = 1,
                            SelectorVersion = 1,
                            ShareIntentPatternsJson = "[\"poshmark://closet/([^/]+)\"]",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UrlPatternsJson = "[\"https?://(?:www\\\\.)?poshmark\\\\.com/closet/([^/?]+)\"]",
                            UsernameSelectorsJson = "[{\"priority\":1,\"selector\":\"h1.closet-title\",\"type\":\"css\"}]",
                            VerificationMethodsJson = "[\"ShareIntent\",\"TokenInBio\"]"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BackoffStrategy = 0,
                            BioFieldSelector = "div.shop-info p.announcement",
                            BrandColor = "#F56400",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Etsy",
                            Domain = "etsy.com",
                            LogoUrl = "https://www.etsy.com/logo.png",
                            PlatformId = "etsy",
                            RateLimitPerMinute = 10,
                            RatingFormat = 0,
                            RatingMax = 5.0m,
                            RatingSelectorsJson = "[{\"priority\":1,\"selector\":\"span[data-reviews-rating]\",\"type\":\"css\"}]",
                            RatingSourceMode = 1,
                            ReviewCountSelectorsJson = "[{\"priority\":1,\"selector\":\"span.reviews-count\",\"type\":\"css\"}]",
                            SelectorVersion = 1,
                            ShareIntentPatternsJson = "[\"etsy://shop/([^/]+)\"]",
                            Status = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UrlPatternsJson = "[\"https?://(?:www\\\\.)?etsy\\\\.com/shop/([^/?]+)\"]",
                            UsernameSelectorsJson = "[{\"priority\":1,\"selector\":\"h1.shop-name\",\"type\":\"css\"}]",
                            VerificationMethodsJson = "[\"ShareIntent\",\"TokenInBio\"]"
                        });
                });

            modelBuilder.Entity("SilentID.Api.Models.ProfileLinkEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsentConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentIpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvidenceState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExtractionConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractionMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("HtmlExtractionMatch")
                        .HasColumnType("boolean");

                    b.Property<int>("IntegrityScore")
                        .HasColumnType("integer");

                    b.Property<string>("LinkState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ManualScreenshotCount")
                        .HasColumnType("integer");

                    b.Property<string>("ManualScreenshotUrlsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextReverifyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OwnershipLockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlatformRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ProfileJoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScrapeDataJson")
                        .HasColumnType("text");

                    b.Property<bool>("ShowOnPassport")
                        .HasColumnType("boolean");

                    b.Property<string>("SnapshotHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UsernameMatchScore")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationLevel")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProfileLinkEvidences");
                });

            modelBuilder.Entity("SilentID.Api.Models.ReceiptEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailMetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("EvidenceState")
                        .HasColumnType("integer");

                    b.Property<string>("ForwardingAlias")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("FraudFlag")
                        .HasColumnType("boolean");

                    b.Property<int>("IntegrityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Item")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<bool>("RawEmailDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RawHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RawHash");

                    b.HasIndex("UserId");

                    b.ToTable("ReceiptEvidences");
                });

            modelBuilder.Entity("SilentID.Api.Models.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("RefereeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RefereePointsAwarded")
                        .HasColumnType("integer");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ReferrerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReferrerPointsAwarded")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SignedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.HasIndex("ReferralCode");

                    b.HasIndex("ReferrerId");

                    b.HasIndex("Status");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("SilentID.Api.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("Status");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("SilentID.Api.Models.ReportEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OCRText")
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportEvidences");
                });

            modelBuilder.Entity("SilentID.Api.Models.RiskSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("RiskSignals");
                });

            modelBuilder.Entity("SilentID.Api.Models.ScreenshotEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvidenceState")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("FraudFlag")
                        .HasColumnType("boolean");

                    b.Property<int>("IntegrityScore")
                        .HasColumnType("integer");

                    b.Property<string>("OCRText")
                        .HasColumnType("text");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScreenshotEvidences");
                });

            modelBuilder.Entity("SilentID.Api.Models.SecurityAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("SecurityAlerts");
                });

            modelBuilder.Entity("SilentID.Api.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SilentID.Api.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StripeSubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("SilentID.Api.Models.TrustScoreSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BehaviourScore")
                        .HasColumnType("integer");

                    b.Property<string>("BreakdownJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvidenceScore")
                        .HasColumnType("integer");

                    b.Property<int>("IdentityScore")
                        .HasColumnType("integer");

                    b.Property<int>("PeerScore")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("UrsScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("TrustScoreSnapshots");
                });

            modelBuilder.Entity("SilentID.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("integer");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<string>("AppleUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GoogleUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPasskeyEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReferredByCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SignupDeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SignupIP")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SilentID.Api.Models.AuthDevice", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany("AuthDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.ExternalRating", b =>
                {
                    b.HasOne("SilentID.Api.Models.ProfileLinkEvidence", "ProfileLink")
                        .WithMany()
                        .HasForeignKey("ProfileLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileLink");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.IdentityVerification", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("SilentID.Api.Models.IdentityVerification", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.MutualVerification", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SilentID.Api.Models.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("SilentID.Api.Models.PasskeyCredential", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.ProfileLinkEvidence", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.ReceiptEvidence", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.Referral", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SilentID.Api.Models.User", "Referrer")
                        .WithMany()
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Referee");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("SilentID.Api.Models.Report", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SilentID.Api.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("SilentID.Api.Models.ReportEvidence", b =>
                {
                    b.HasOne("SilentID.Api.Models.Report", "Report")
                        .WithMany("Evidence")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SilentID.Api.Models.RiskSignal", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.ScreenshotEvidence", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.SecurityAlert", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.Session", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.Subscription", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.TrustScoreSnapshot", b =>
                {
                    b.HasOne("SilentID.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentID.Api.Models.Report", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("SilentID.Api.Models.User", b =>
                {
                    b.Navigation("AuthDevices");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
